const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.jumpthru,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.gamepad,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Jumpthru: 0},
	{Solid: 0},
	{Ground1: 0},
	{Physics: 0},
	{Ground2: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{Player: 0},
	{Spikes: 0},
	{water: 0},
	{Coin: 0},
	{Tree: 0},
	{Sprite: 0},
	{Rocket: 0},
	{CheckPoint: 0},
	{Spring: 0},
	{Sprite3: 0},
	{Patrol: 0},
	{Enemy: 0},
	{Border: 0},
	{LivesLabel: 0},
	{LivesText: 0},
	{MenuScreen: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{Sine: 0},
	{MovingPlataform: 0},
	{Audio: 0},
	{Touch: 0},
	{Gamepad: 0},
	{Score: 0},
	{Lives: 0},
	{StartPositionX: 0},
	{StartPositionY: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Ground1: class extends self.ITiledBackgroundInstance {},
	Ground2: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Spikes: class extends self.ITiledBackgroundInstance {},
	water: class extends self.ITiledBackgroundInstance {},
	Coin: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Rocket: class extends self.ISpriteInstance {},
	CheckPoint: class extends self.ISpriteInstance {},
	Spring: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Border: class extends self.ISpriteInstance {},
	LivesLabel: class extends self.ITextInstance {},
	LivesText: class extends self.ITextInstance {},
	MenuScreen: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	MovingPlataform: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {}
}